package ch.kanti_wohlen.klassenkasse.framework;

import org.eclipse.jdt.annotation.Nullable;

import ch.kanti_wohlen.klassenkasse.util.MonetaryValue;

/**
 * Represents a class which many {@linkplain User Users} can be part of.
 * <p>
 * A {@code StudentClass} is made up of an ID, a name, its rounding value and a cached value of its balance.
 * </p>
 */
public final class StudentClass implements LocallyIdentifiable<Integer> {

	private final int id;

	private String className;
	private MonetaryValue rounding;
	private MonetaryValue balance;

	/**
	 * Creates a new {@link StudentClass} with an ID generated by a {@link Host}.
	 * 
	 * @param host
	 *            the host which is used to generate a new {@code StudentClass} ID,
	 *            cannot be {@code null}
	 * @param name
	 *            the name of this {@code StudentClass}, cannot be {@code null} or empty
	 */
	public StudentClass(Host host, String name) {
		id = host.getIdProvider().generateClassId();
		className = name;
		rounding = MonetaryValue.ZERO;
		balance = MonetaryValue.ZERO;
	}

	/**
	 * Creates a {@link StudentClass} with a given ID.
	 * <p>
	 * Use this constructor when loading a {@code StudentClass} from stored data or similar.
	 * </p>
	 * 
	 * @param id
	 *            the local ID to be set
	 * @param name
	 *            the name of this {@code StudentClass}, cannot be {@code null} or empty
	 * @param rounding
	 *            the rounding value, cannot be {@code null}
	 * @param balance
	 *            the rounded balance, cannot be {@code null}
	 */
	public StudentClass(int id, String name, MonetaryValue rounding, MonetaryValue balance) {
		this.id = id;
		this.className = name;
		this.rounding = rounding;
		this.balance = balance;
	}

	@SuppressWarnings("null")
	@Override
	public Integer getLocalId() {
		return id;
	}

	/**
	 * Gets the name of this {@link StudentClass}.
	 * 
	 * @return its name, never {@code null} or empty
	 */
	public String getName() {
		return className;
	}

	/**
	 * Sets a new name for this {@link StudentClass}.
	 * 
	 * @param newName
	 *            the new name, not {@code null} or empty
	 */
	public void setName(String newName) {
		className = newName;
	}

	/**
	 * Gets the rounding value of this {@link StudentClass}.
	 * 
	 * @return the rounding value, never {@code null}
	 */
	public MonetaryValue getRoundingValue() {
		return rounding;
	}

	/**
	 * Sets the rounding value of this {@link StudentClass}.
	 * 
	 * @param newRoundingValue
	 *            the rounding value to be set, never {@code null}
	 */
	public void setRoundingValue(MonetaryValue newRoundingValue) {
		rounding = newRoundingValue;
	}

	/**
	 * Gets the rounded balance of this {@link StudentClass}.
	 * 
	 * @return its rounded balance, will never be {@code null}
	 */
	public MonetaryValue getRoundedBalance() {
		return balance;
	}

	/**
	 * Sets the rounded balance of this {@link StudentClass}.
	 * 
	 * @param newBalance
	 *            the new balance, cannot be {@code null}
	 */
	public void setRoundedBalance(MonetaryValue newBalance) {
		balance = newBalance;
	}

	/**
	 * Gets the balance of this {@link StudentClass},
	 * which is the sum of its rounded balance and its rounding value.
	 * 
	 * @return the balance, will never be {@code null}
	 */
	public MonetaryValue getBalance() {
		return balance.add(rounding);
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (obj instanceof StudentClass) {
			return id == ((StudentClass) obj).id;
		} else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return id;
	}
}
