package ch.kanti_wohlen.klassenkasse.framework;

import org.eclipse.jdt.annotation.Nullable;

import ch.kanti_wohlen.klassenkasse.util.MonetaryValue;

/**
 * Represents a user, which can be a student, a teacher or an administrator.
 * <p>
 * A {@code User} is uniquely identifiable by its ID or its user name. Every user has a {@link Role} assigned to it and
 * must be in a {@link StudentClass}.
 * </p>
 * <p>
 * Administrators and the like shall be in the {@link StudentClass} with the ID 0, which will not be displayed.
 * </p>
 * 
 * @author Roger Baumgartner
 */
public final class User implements LocallyIdentifiable<Integer> {

	/**
	 * This {@code enum} represents how a {@link User}'s name is formatted by default.
	 */
	public static enum NamingMode {
		/**
		 * Format: {@code FirstName LastName}
		 */
		FIRST_NAME_FIRST,

		/**
		 * Format: {@code LastName, FirstName}
		 */
		LAST_NAME_FIRST
	}

	private static NamingMode defaultNamingMode = NamingMode.FIRST_NAME_FIRST;

	private final int id;

	private int classId;
	private int roleId;
	private String firstName;
	private String lastName;
	private String username;
	private MonetaryValue balance;

	/**
	 * Creates a new {@code User} with an ID generated by a {@link Host}.
	 * 
	 * @param host
	 *            the host which is used to generate a new {@code User} ID,
	 *            cannot be {@code null}
	 * @param classId
	 *            the ID of the {@link StudentClass} this {@code User} is in
	 * @param roleId
	 *            the ID of the {@link Role} this {@code User} is in
	 * @param firstName
	 *            the first name, cannot be {@code null} or empty
	 * @param lastName
	 *            the last name, cannot be {@code null} or empty
	 * @param username
	 *            the user name, cannot be {@code null} or empty
	 */
	public User(Host host, int classId, int roleId, String firstName, String lastName, String username) {
		if (firstName.isEmpty()) throw new IllegalArgumentException("First name can't be empty.");
		if (lastName.isEmpty()) throw new IllegalArgumentException("Last name can't be empty.");
		if (username.isEmpty()) throw new IllegalArgumentException("User name can't be empty.");

		this.id = host.getIdProvider().generateUserId();

		this.classId = classId;
		this.roleId = roleId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		balance = MonetaryValue.ZERO;
	}

	/**
	 * Creates a {@code User} with a given ID.
	 * <p>
	 * Use this constructor when loading a {@code User} from stored data or similar.
	 * </p>
	 * 
	 * @param id
	 *            the local ID to be set
	 * @param classId
	 *            the ID of the {@link StudentClass} this {@code User} is in
	 * @param roleId
	 *            the ID of the {@link Role} this {@code User} is in
	 * @param firstName
	 *            the first name, cannot be {@code null} or empty
	 * @param lastName
	 *            the last name, cannot be {@code null} or empty
	 * @param username
	 *            the user name, cannot be {@code null} or empty
	 * @param value
	 *            the cached balance of all {@link Payment}s
	 */
	public User(int id, int classId, int roleId, String firstName, String lastName, String username, MonetaryValue value) {
		if (firstName.isEmpty()) throw new IllegalArgumentException("First name can't be empty.");
		if (lastName.isEmpty()) throw new IllegalArgumentException("Last name can't be empty.");
		if (username.isEmpty()) throw new IllegalArgumentException("User name can't be empty.");

		this.id = id;

		this.classId = classId;
		this.roleId = roleId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		balance = value;
	}

	/**
	 * Gets the ID of this {@code User}, local to the current system.
	 * 
	 * @return the local ID
	 */
	@SuppressWarnings("null")
	@Override
	public Integer getLocalId() {
		return id;
	}

	/**
	 * Gets the ID of this {@code User}'s {@link StudentClass}.
	 * 
	 * @return the {@code StudentClass} ID
	 * 
	 * @see #getStudentClass(Host)
	 */
	public int getStudentClassId() {
		return classId;
	}

	/**
	 * Gets the {@link StudentClass} that is associated to the stored class ID.
	 * 
	 * @param host
	 *            the {@link Host} used to look up the {@code StudentClass}
	 * @return the {@code User}'s {@code StudentClass}
	 * 
	 * @see #getStudentClassId()
	 */
	public StudentClass getStudentClass(Host host) {
		StudentClass studentClass = host.getClassById(classId);
		if (studentClass == null) {
			throw new IllegalStateException("The host does not contain this User's StudentClass");
		}
		return studentClass;
	}

	/**
	 * Sets the stored {@link StudentClass} ID by looking up the {@linkplain StudentClass#getLocalId() localID} of a
	 * {@code StudentClass}.
	 * 
	 * @param newStudentClass
	 *            the {@code StudentClass}, cannot be {@code null}
	 * 
	 * @see #setStudentClass(int)
	 */
	public void setStudentClass(StudentClass newStudentClass) {
		classId = newStudentClass.getLocalId();
	}

	/**
	 * Sets the stored {@link StudentClass} ID.
	 * The ID set here is not checked for validity.
	 * 
	 * @param newClassId
	 *            the ID of a valid {@code StudentClass}
	 * 
	 * @see #setStudentClass(StudentClass)
	 */
	public void setStudentClass(int newClassId) {
		classId = newClassId;
	}

	/**
	 * Gets the ID of this {@code User}'s {@link Role}.
	 * 
	 * @return the {@code Role} ID
	 * 
	 * @see #getRole(Host)
	 */
	public int getRoleId() {
		return roleId;
	}

	/**
	 * Gets the {@link Role} that is associated to the stored role ID.
	 * 
	 * @param host
	 *            the {@link Host} used to look up the {@code Role}
	 * @return the {@code User}'s {@code Role}
	 * 
	 * @see #getRoleId()
	 */
	public Role getRole(Host host) {
		Role role = host.getRoleById(roleId);
		if (role == null) {
			throw new IllegalStateException("The host does not contain this User's Role");
		}
		return role;
	}

	/**
	 * Sets the stored {@link Role} ID by looking up the {@linkplain Role#getLocalId() localID} of a {@code Role}.
	 * 
	 * @param newRole
	 *            the {@code Role}, cannot be {@code null}
	 * 
	 * @see #setRole(int)
	 */
	public void setRole(Role newRole) {
		roleId = newRole.getLocalId();
	}

	/**
	 * Sets the stored {@link Role} ID.
	 * The ID set here is not checked for validity.
	 * 
	 * @param newRoleId
	 *            the ID of a valid {@code Role}
	 * 
	 * @see #setRole(Role)
	 */
	public void setRole(int newRoleId) {
		roleId = newRoleId;
	}

	/**
	 * Gets the first name of this {@code User}
	 * 
	 * @return the first name
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Sets the first name of this {@code User}
	 * 
	 * @param newFirstName
	 *            the first name, cannot be {@code null} or empty
	 * @throws IllegalArgumentException
	 *             if the first name is empty
	 */
	public void setFirstName(String newFirstName) {
		if (newFirstName.isEmpty()) throw new IllegalArgumentException("Empty first name.");
		firstName = newFirstName;
	}

	/**
	 * Gets the last name of this {@code User}
	 * 
	 * @return the last name
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Sets the last name of this {@code User}
	 * 
	 * @param newLastName
	 *            the last name, cannot be {@code null} or empty
	 * @throws IllegalArgumentException
	 *             if the last name is empty
	 */
	public void setLastName(String newLastName) {
		if (newLastName.isEmpty()) throw new IllegalArgumentException("Empty last name.");
		lastName = newLastName;
	}

	/**
	 * Gets the {@code User}'s full name, using the preferred format set by #setDefaultNamingMode()
	 * 
	 * @return the full name of the {@code User}, consisting of the first name
	 *         and the last name.
	 * 
	 * @see NamingMode#FIRST_NAME_FIRST
	 * @see #getFullName(NamingMode)
	 */
	public String getFullName() {
		return getFullName(defaultNamingMode);
	}

	/**
	 * Gets the {@code User}'s full name, using the formatting given by a {@link NamingMode}.
	 * 
	 * @param namingMode
	 *            the {@code NamingMode} to be used when creating the full name.
	 * @return the full name of the {@code User}, consisting of the first name
	 *         and
	 *         the last name.
	 * 
	 * @see NamingMode
	 */
	public String getFullName(NamingMode namingMode) {
		switch (namingMode) {
		case FIRST_NAME_FIRST:
			return firstName + " " + lastName;
		case LAST_NAME_FIRST:
			return lastName + ", " + firstName;
		default:
			throw new IllegalArgumentException("Illegal naming mode parameter.");
		}
	}

	/**
	 * Gets this {@code User}'s unique user name.
	 * 
	 * @return this User's user name. Will not be {@code null}.
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * Sets a new user name for this {@code User}.
	 * <p>
	 * Please note that the user name should be unique. However, this method does not check if it really is unique.
	 * </p>
	 * 
	 * @param newUsername
	 *            the new user name, cannot be {@code null} or empty
	 * @throws IllegalArgumentException
	 *             if the new user name is empty
	 */
	public void setUsername(String newUsername) {
		if (newUsername.isEmpty()) throw new IllegalArgumentException("Empty user name.");
		username = newUsername;
	}

	/**
	 * Gets the this {@linkplain User User's} balance as a {@link MonetaryValue}.
	 * 
	 * @return the balance, never {@code null}
	 */
	public MonetaryValue getBalance() {
		return balance;
	}

	/**
	 * Sets the balance of this {@link User} to a new {@link MonetaryValue}.
	 * 
	 * @param newBalance
	 *            the new balance to be used
	 */
	public void setBalance(MonetaryValue newBalance) {
		balance = newBalance;
	}

	@Override
	public boolean equals(@Nullable Object obj) {
		if (obj instanceof User) {
			return id == ((User) obj).id;
		} else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return id;
	}

	/**
	 * Gets the default {@link NamingMode} to be used when calling {@link #getFullName()}.
	 * 
	 * @return the default {@code NamingMode}, never {@code null}, defaults to {@link NamingMode#FIRST_NAME_FIRST}
	 */
	public static NamingMode getDefaultNamingMode() {
		return defaultNamingMode;
	}

	/**
	 * Sets the default {@link NamingMode} to be used when calling {@link #getFullName()}.
	 * 
	 * @param newNamingMode
	 *            the new {@code NamingMode}
	 */
	public static void setDefaultNamingMode(NamingMode newNamingMode) {
		defaultNamingMode = newNamingMode;
	}
}
